{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "businessplanner.fullname" . }}-redis
  labels:
    {{- include "businessplanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    {{- include "businessplanner.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
{{- end -}}
