{{- if .Values.sso.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "businessplanner.fullname" . }}-sso
  labels:
    {{- include "businessplanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: sso
spec:
  replicas: {{ .Values.sso.replicas }}
  selector:
    matchLabels:
      {{- include "businessplanner.selectorLabels" (dict "ctx" . "component" "sso") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "businessplanner.selectorLabels" (dict "ctx" . "component" "sso") | nindent 8 }}
    spec:
      containers:
        - name: sso
          image: {{ include "businessplanner.image" (dict "ctx" . "image" .Values.sso.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.sso.port }}
          env:
            - name: DB_HOST
              value: {{ include "businessplanner.fullname" . }}-postgres
            - name: REDIS_HOST
              value: {{ include "businessplanner.fullname" . }}-redis
{{- end -}}
